name: mrl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - mpi4py
  - cmake
  - qt=5.12.5
  - gxx_linux-64
  - pip
  - pip:
    - gym3
    - torch
    - pandas
    - matplotlib
    - numpy>=1.21
    - gym
    - filelock
    - tensorboard
    - arrow
    - tqdm
    - fire
    # Dev
    - pytest
    - hypothesis
    - mypy
    - pylint
    - black