name: mrl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - mpi4py
  - c-compiler
  - cmake
  - qt=5.12.5
  - pip
  - pip:
    - gym3
    - procgen
    - torch
    - pandas
    - matplotlib
    - numpy>=1.21
    - gym
    - filelock
    - fire
    # Dev
    - pytest
    - hypothesis
    - mypy
    - pylint
    - black