name: mrl
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - mpi4py
  - cmake
  - qt=5.12.5
  - java-jdk 
  - pip
  - redis-cli
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
