name: mrl
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - mpi4py
  - cmake
  - qt=5.12.5
  - java-jdk 
  - pip
  - pip:
    - gym3
    - torch
    - psutil
    - pandas
    - matplotlib
    - numpy>=1.21
    - gym
    - filelock
    - tensorboard
    - arrow
    - tqdm
    - fire
    - argh
    - scipy
    - gputil
    - hydra-core
    - pyyaml
    - git+https://github.com/jordan-schneider/omegaconf.git
    # Dev
    - pytest
    - hypothesis
    - mypy
    - pylint
    - black
